[package]
name = "issuer_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13.1"
canister_sig_util = { git = "https://github.com/dfinity/internet-identity.git" }
internet_identity_interface = { git = "https://github.com/dfinity/internet-identity.git" }
vc_util = { git = "https://github.com/dfinity/internet-identity.git" }
asset_util = { git = "https://github.com/dfinity/internet-identity.git" }
