[package]
name = "issuer_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-stable-structures = "0.6.3"
candid = "0.10"
ic-cdk = "0.13.1"
canister_sig_util = { git = "https://github.com/dfinity/internet-identity.git" }
internet_identity_interface = { git = "https://github.com/dfinity/internet-identity.git" }
vc_util = { git = "https://github.com/dfinity/internet-identity.git" }
asset_util = { git = "https://github.com/dfinity/internet-identity.git" }
k256 = "0.13.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
hex = "0.4.3"
serde_json = "1.0.114"
